{
   "info":{
      "social":{
         "twitter_handle":"https://twitter.com/PolitikozNft",
         "discord_handle":"discord.gg/BBFkgV4PYS",
         "github_handle":"https://github.com/politikoz"
      }
   }
}
